name: "Update challenges on owasp-juice.shop"

on:
  push:
    branches: [ master ]
    paths:
      - 'data/static/challenges.yml'

jobs:
  UpdateChallengesOnWebsite:
    if: github.repository == 'juice-shop/juice-shop'
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
      with:
        token: ${{ secrets.BOT_TOKEN }}
        repository: OWASP/www-project-juice-shop
        ref: master
    - name: Update challenges.yml
      run: |
        cd _data/
        rm challenges.yml
        wget https://raw.githubusercontent.com/juice-shop/juice-shop/master/data/static/challenges.yml
    - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a #v4.16.0
      with:
        commit_message: "Auto-update challenges.yml from ${{ github.sha }}"
        branch: master
        commit_options: '--signoff'

        # Optional commit user and author settings
        commit_user_name: JuiceShopBot
        commit_user_email: 61591748+JuiceShopBot@users.noreply.github.com
        commit_author: JuiceShopBot <61591748+JuiceShopBot@users.noreply.github.com>
