name: "Update news on owasp-juice.shop"

on:
  release:
    types: [ published ]

jobs:
  UpdateNewsOnWebsite:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
      with:
        token: ${{ secrets.BOT_TOKEN }}
        repository: OWASP/www-project-juice-shop
        branch: master
    - name: Update tab_news.md
      run: |
        sed -i 's/<!-- next:juice-shop -->/<!-- next:juice-shop -->\n* ${{ github.event.release.published_at }}: juice-shop [`${{ github.event.release.tag_name }}`](https:\/\/github.com\/juice-shop\/juice-shop\/releases\/tag\/${{ github.event.release.tag_name }})/' tab_news.md
    - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a #v4.16.0
      with:
        commit_message: "Add juice-shop ${{ github.event.release.tag_name }} release notes to tab_news.md"
        branch: master
        commit_options: '--signoff'

        # Optional commit user and author settings
        commit_user_name: JuiceShopBot
        commit_user_email: 61591748+JuiceShopBot@users.noreply.github.com
        commit_author: JuiceShopBot <61591748+JuiceShopBot@users.noreply.github.com>
